export const APP_CONFIG = {
	APP_MODE: process.env.NODE_ENV,
	PORT: process.env.PORT ?? 4200,
	HOSTNAME: process.env.HOSTNAME,
	CLIENT_URL: process.env.CLIENT_URL,
	CLIENT_PROFILE_URL: process.env.CLIENT_PROFILE_URL,
	API_URL: process.env.API_URL,
	USER_DEFAULT_PASS: process.env.USER_DEFAULT_PASS,
} as const

export const APP_EXPIRES_CONFIG = {
	EXPIRES_USER_VERIFY: process.env.EXPIRES_USER_VERIFY,
	EXPIRES_USER_REMOVE_VERIFY: process.env.EXPIRES_USER_REMOVE_VERIFY,
	EXPIRES_USER_RESET_PASSWORD_VERIFY:
		process.env.EXPIRES_USER_RESET_PASSWORD_VERIFY,
	EXPIRES_USER_VERIFY_UNIT_CASE: process.env.EXPIRES_USER_VERIFY_UNIT_CASE,
	EXPIRES_USER_REMOVE_VERIFY_UNIT_CASE:
		process.env.EXPIRES_USER_REMOVE_VERIFY_UNIT_CASE,
	EXPIRES_USER_RESET_PASSWORD_VERIFY_UNIT_CASE:
		process.env.EXPIRES_USER_RESET_PASSWORD_VERIFY_UNIT_CASE,
} as const

export const APP_SESSIONS_CONFIG = {
	JWT_ACCESS_KEY: process.env.JWT_ACCESS_KEY,
	JWT_REFRESH_KEY: process.env.JWT_REFRESH_KEY,
	JWT_ACCESS_EXPIRES: process.env.JWT_ACCESS_EXPIRES,
	JWT_REFRESH_EXPIRES: process.env.JWT_REFRESH_EXPIRES,
	JWT_ACCESS_EXPIRES_UNIT_CASE: process.env.JWT_ACCESS_EXPIRES_UNIT_CASE,
	JWT_REFRESH_EXPIRES_UNIT_CASE: process.env.JWT_REFRESH_EXPIRES_UNIT_CASE,
} as const

export const APP_EMAIL_CONFIG = {
	SMTP_HOST: process.env.SMTP_HOST,
	SMTP_PORT: Number(process.env.SMTP_PORT),
	SMTP_USER: process.env.SMTP_USER,
	SMTP_PASSWORD: process.env.SMTP_PASSWORD,
} as const

export const APP_ADMIN_CONFIG = {
	ADMIN_EMAIL: process.env.ADMIN_EMAIL,
	ADMIN_PHONE: process.env.ADMIN_PHONE,
	ADMIN_IS_VERIFY: Boolean(process.env.ADMIN_IS_VERIFY),
	ADMIN_PASS: process.env.ADMIN_PASS,
} as const
